.TH runit-reboot 8
.SH NAME
runit-reboot \- reboot the system
.SH SYNOPSIS
.B init
6
.br
.B runit-reboot
.SH DESCRIPTION
.B runit-reboot
causes the Unix process no 1
.BR runit (8)
to reboot the system. Normally
.B runit-reboot
is run by
.BR runit-init (8)
if called as
.B init 6\fR.
.P
To signal
.BR runit (8)
the system reboot request,
.B runit-reboot
touches the /etc/runit/reboot and /etc/runit/stopit files. Then a CONT
signal is sent to
.BR runit (8).
.SH EXIT CODES
.B runit-reboot
always returns 0.
.SH SEE ALSO
runit-init(8),
runit(8),
runit-halt(8)
.SH AUTHOR
Gerrit Pape <pape@smarden.org>
