.TH runsvstat 8
.SH NAME
runsvstat \- prints the status of services monitored by
.BR runsv (8).
.SH SYNOPSIS
.B runsvstat
[
.B \-l
]
.I services
.SH DESCRIPTION
.I services
consists of one or more arguments, each argument naming a directory.
.P
.B runsvstat
checks for each directory if
.BR runsv (8)
is successfully running this
.IR service ,
and if so, prints one human-readable line reporting the status of this
.IR service .
Optionally
.BR runsvstat (8)
prints a second line, also in human-readable format, reporting the status
of the corresponding
.I log
.IR service .
.SH OPTIONS
.TP
.B \-l
log service. Check for each
.I service
if there exists a corresponding
.I log
.IR service .
If so, print an additional, indented, line reporting the status of the
.I log
.IR service .
.SH EXIT CODES
.B runsvstat
exits 0, if the states of all
.I services
were reported successfully.
.P
For each
.I service
that caused an error (e.g. the directory is not controlled by a
.BR runsv (8)
process),
.B runsvstat
increases the exit code by one and exits non zero. The maximum is 100.
.P
.B runsvstat
exits 111 on error.
.SH SEE ALSO
runsvctrl(8),
runit(8),
runit-init(8),
runsvdir(8),
runsv(8),
svwaitdown(8),
svwaitup(8)
.P
 http://smarden.org/runit/
.SH AUTHOR
Gerrit Pape <pape@smarden.org>
