#!/bin/sh
# system one time tasks
trap : 2
trap : 3

/bin/sh /etc/rc autoboot && exit 0

# /etc/rc crashed, start emergency shell.
echo '/etc/rc failed. Press <enter> for emergency shell...'
read input
/bin/sh -p
/sbin/reboot

exit
