#!/bin/sh
# system one time tasks

/bin/sh /etc/rc autoboot && exit 0

# /etc/rc crashed, start emergency shell.
echo '/etc/rc failed. Press <enter> for emergency shell...'
read input
/bin/sh -p
exec /sbin/reboot
