#!/bin/sh
exec 2>&1

LAST=0
test -r /etc/runit/reboot && LAST=6

echo 'Waiting for getties to stop...'
/command/svwaitdown -xk -t14 /service/getty-*

echo 'Waiting for services to stop...'
/command/svwaitdown -xk -t350 /service/*

echo 'Shutdown...'
/etc/init.d/rc $LAST

exit 0
