#!/bin/sh
exec 2>&1

PATH=/command:/sbin:/bin:/usr/sbin:/usr/bin

echo 'Waiting for services to stop...'
svwaitdown -xk -t350 /service/*

echo 'Shutdown...'
if test -x /etc/runit/reboot; then
  exec reboot
else
  exec halt
fi
