#!/bin/sh
PATH=/bin:/sbin:/command

echo 'Stopping services...'
svc -d /service/*
svwaitdown -t350 /service/* || ( echo 'Killing services...' ; \
  svc -k /service/* ; svwaitdown /service/* )

echo 'Stopping log services...'
svc -d /service/*/log
svwaitdown -t35 /service/*/log || ( echo 'Killing log services...' ; \
  svc -k /service/*/log ; svwaitdown /service/*/log )

echo 'Shutdown...'
if test -r /etc/runit/reboot; then
  exec reboot
else
  exec halt
fi

exit 0
