#!/bin/sh

##
# runit
##

. /etc/rc.common

StartService() {
  ConsoleMessage "Starting runit service supervision"
  /bin/csh -cf '/sbin/runsvdir-start &'
}
StopService() {
  ConsoleMessage "Stopping runit service supervision"
  sv -w196 force-stop /var/service/*
  sv exit /var/service/*
}
RestartService() {
  return 0
}

RunService "$1"
