#!/bin/sh
exec 2>&1

PATH=/bin:/sbin:/command

echo 'Waiting for getties to stop...'
svwaitdown -xk -t14 /service/getty-*

echo 'Waiting for services to stop...'
svwaitdown -xk -t350 /service/*

echo 'Shutdown...'
if test -r /etc/runit/reboot; then
  exec reboot
else
  exec halt
fi

exit 0
