#!/bin/sh
exec 2>&1

PATH=/sbin:/bin:/usr/sbin:/usr/bin

LAST=0
test -r /etc/runit/reboot && LAST=6

echo 'Waiting for services to stop...'
svwaitdown -xk -t350 /var/service/*

echo 'Waiting for getties to stop...'
svwaitdown -xk -t14 /var/service/getty-*

echo 'Shutdown...'
/etc/init.d/rc $LAST
