.TH RUNSVDIR-START 8 "22 February 2004"
.SH NAME
runsvdir-start \- monitor and start runsv(8) processes in /var/service
.SH SYNOPSIS
\fBrunsvdir-start\fP
.SH DESCRIPTION
Intended to be run at boot time, the script monitors and starts processes
in the \fB/var/service\fP directory.
.SH EXAMPLE
Include the following line into your \fB/etc/inittab\fP:

  \fBSV:123456:respawn:/usr/sbin/runsvdir-start\fP
.SH FILES
 /var/service/
 /etc/inittab
.SH SEE ALSO
runsvdir(8), runsv(8), inittab(5)

http://smarden.org/runit/
.SH AUTHOR
This manpage was originally written by Bastian Kleineidam
<calvin@debian.org> for the Debian distribution of runit
(but may be used by others).

The main author of runit is Gerrit Pape <pape@smarden.org>.
