#!/bin/sh -e

umask 022
test -d package || ( echo 'Wrong working directory.'; exit 1 ) || exit 1
test -d compile || ( echo 'Wrong working directory.'; exit 1 ) || exit 1

echo 'Checking commands in ./command...'
( cd compile; exec make check ) || exit 1
