#!/bin/sh -e

umask 022
test -d package || ( echo 'Wrong working directory.'; exit 1 )
test -d src || ( echo 'Wrong working directory.'; exit 1 )

here=`env - PATH=$PATH pwd`

echo 'Copying ./etc/runit into /etc...'
rm -f /etc/runit'{new}'
cp -pr ./etc/runit /etc/runit'{new}'
mv -f /etc/runit'{new}' /etc/runit

echo 'Copying commands into /sbin...'
for i in `cat package/commands`
do
  rm -f /sbin/$i'{new}'
  cp -p command/$i /sbin/$i'{new}'
  mv -f /sbin/$i'{new}' /sbin/$i
done

echo 'Copying original /sbin/init to /sbin/init.orig...'
cp /sbin/init /sbin/init.orig

echo 'Linking /sbin/runit-init to /sbin/init...'
rm -f /sbin/init'{new}'
ln -s /sbin/runit-init /sbin/init'{new}'
mv -f /sbin/init'{new}' /sbin/init
