#!/bin/sh
exec 2>&1

PATH=/sbin:/bin:/command

LAST=0
test -r /etc/runit/reboot && LAST=6

echo 'Waiting for getties to stop...'
svwaitdown -xk -t14 /service/getty-*

echo 'Waiting for services to stop...'
svwaitdown -xk -t350 /service/*

echo 'Shutdown...'
/etc/init.d/rc $LAST
