#!/bin/sh

LAST=0
test -r /etc/runit/reboot && LAST=6

echo 'Stopping services...'
/command/svc -d /service/*
/bin/sleep 5
echo 'Stopping log services...'
/command/svc -d /service/*/log
/bin/sleep 5

/etc/init.d/rc $LAST

exit 0
